APPfoto/urls.py
from django.urls import path
from . import views

app_name = "APPfoto"

urlpatterns = [
    path(" /", views.home_view, name="home"),
    path("ricerca", views.search, name="cercaFoto"),
    path("ricerca/<str:sstring>/<str:where>", views.FotoListaRicercataView.as_view(), name="ricerca_risultati"),
    path("crea_foto/", views.CreateFotoView.as_view(), name="creafoto"),
    path("lista_foto/",views.FotoListView.as_view(), name="listafoto"),
    path("search_wrong_colour/", views.SearchWrongColourView.as_view(), name="search_wrong_colour"),
    path("situation/", views.my_situation, name="situation")

]

foto_commerce/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('APPfoto/', include('APPfoto.urls')),
re_path(r"^$|^\/$|^home\/$",home,name="home"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("registrafotografo", FotografoCreateView.as_view(), name="registrafotografo")
]

APPfoto/models.py
from django.db import models


# Create your models here.

from django.db import models


class Foto(models.Model):
    COLOUR_CHOICES = [
        ("Black", "Black"),
        ("Dark Blue", "Dark Blue"),
        ("Green", "Green"),
        ("Grey", "Grey"),
        ("Light Blue", "Light Blue"),
        ("Orange", "Orange"),
        ("Pink", "Pink"),
        ("Purple", "Purple"),
        ("Red", "Red"),
        ("White", "White"),
        ("Yellow", "Yellow"),
    ]

    name = models.CharField(max_length=50)
    artist_name = models.CharField(max_length=50)
    main_colour = models.CharField(max_length=20, choices=COLOUR_CHOICES)
    landscape = models.BooleanField()
    actual_photo = models.ImageField(upload_to='static/photos')
    def __str__(self):
        if(self.landscape==True):
            return "Nome foto: " + str(self.name) + ", scattata da: " + str(
                self.artist_name) + ", colore principale: " + str(self.main_colour) + ", ed è una foto landscape."
        else:
            return "Nome foto: " + str(self.name) + ", scattata da: " + str(
                self.artist_name) + ", colore principale: " + str(self.main_colour) + ", ed è una foto portrait."

APPfoto/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import *

from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class SearchForm(forms.Form):
    CHOICE_LIST = [
        ("name", "Cerca nome foto"),
        ("artist_name", "Cerca nome fotografo"),
        ("main_colour", "Cerca per colore principale"),
        ("Orientamento", "Cerca per orientamento")
    ]

    COLOUR_CHOICES = ["Black", "Dark Blue", "Green", "Gray", "Light Blue", "Orange", "Pink",
                      "Purple", "Red", "White", "Yellow"]

    helper = FormHelper()
    helper.form_id = 'search_crispy_form'
    helper.form_method = "POST"
    helper.add_input(Submit('submit', 'Cerca'))

    search_string = forms.CharField(label="Cerca qualcosa", max_length=100, min_length=1, required=True)
    search_where = forms.ChoiceField(label="Ricerca per: ", required=True, choices=CHOICE_LIST)



class FotoCrispyForm(forms.ModelForm):

    helper = FormHelper()
    helper.form_id = 'foto-crispy-form'
    helper.form_method = 'POST'
    helper.add_input(Submit('submit','Submit'))

    class Meta:
        model = Foto
        fields = ('name', 'artist_name', 'main_colour', 'landscape')


class CreateFotoForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_id = "addfoto_crispy_form"
    helper.form_method = "POST"
    helper.add_input(Submit("submit", "Aggiungi Foto"))

    class Meta:
        model = Foto
        fields = ["name", "artist_name", "main_colour", "landscape","actual_photo"]

foto_commerce/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group

class CreaUtenteCliente(UserCreationForm):
    def save(self, commit=True):
        user = super().save(commit)
        g = Group.objects.get(name="Clienti")
        g.user_set.add(user)
        return user


class CreaUtenteFotografo(UserCreationForm):

    def save(self, commit=True):
        user = super().save(commit)
        g = Group.objects.get(name="Fotografi")
        g.user_set.add(user)
        return user

APPfoto/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
# Create your views here.


def home_view(request):
    return render(request, template_name="APPfoto/home.html")


from .forms import SearchForm  # Import your form class

from django.shortcuts import render
from django.views import View




class SearchWrongColourView(View):
    template_name = "APPfoto/search_wrong_colour.html"

    def get(self, request, *args, **kwargs):
        form = SearchForm()  # Replace with your actual form class
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):

        if request.method == "POST":
            form = SearchForm(request.POST)
            if form.is_valid():
                sstring = form.cleaned_data.get("search_string")
                where = form.cleaned_data.get("search_where")
                return redirect("APPfoto:ricerca_risultati", sstring, where)
            else:
                context = {'form': form}
            return render(request, self.template_name, context)


class FotoListView(ListView):
    titolo="Abbiamo trovato queste foto"
    model = Foto
    template_name = "APPfoto/lista_foto.html"


from django.contrib import messages


def search(request):
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            sstring = form.cleaned_data.get("search_string")
            where = form.cleaned_data.get("search_where")
            return redirect("APPfoto:ricerca_risultati", sstring, where)

    else:
        form = SearchForm()

    return render(request, "APPfoto/search.html",context= {"form": form})


class FotoListaRicercataView(FotoListView):
    titolo = "risultati ricerca"

    def get_queryset(self):
        sstring = self.kwargs['sstring']
        where = self.kwargs['where']


        if where == "name":
            qq = self.model.objects.filter(name__icontains=sstring)
        elif where == "landscape":
            # Filter using a boolean condition
            qq = self.model.objects.filter(landscape=True)
        elif where == "main_colour":
            # Filter using elements from a list
            COLOUR_CHOICES_to_filter = ["Black","Dark Blue","Green", "Gray", "Light Blue", "Orange", "Pink",
                                        "Purple", "Red", "White", "Yellow"]
            qq = self.model.objects.filter(main_colour__in=sstring)

        else:
            qq = self.model.objects.filter(artist_name__icontains=sstring)

        return qq


class CreateFotoView(CreateView):
    title = "Aggiungi la tua foto alla galleria"
    form_class = CreateFotoForm
    template_name = "APPfoto/create_entry.html"
    success_url = reverse_lazy("APPfoto:home")


@login_required
def my_situation(request):
     user = get_object_or_404(User, pk=request.user.pk)
     return render(request,"APPfoto/situation.html")

foto_commerce/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from .forms import *
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import PermissionRequiredMixin

def home(request):
    return render(request, template_name="home.html")

class UserCreateView(CreateView):
    form_class = CreaUtenteCliente()
    template_name = "user_create.html"
    success_url = reverse_lazy("login")


class FotografoCreateView(PermissionRequiredMixin, UserCreateView):
    permission_required = "is_staff"
    form_class = CreaUtenteFotografo

APPfoto/templates/APPfoto/create_entry.html
{% extends 'base.html' %}

{% block title %} {{ view.title }} {% endblock %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block header1 %}
  <h1> {{ view.title }} </h1>
{% endblock %}

{% block content %}

<br>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Aggiungi Foto</button>
      </form>
    </div>
  </div>
</div>

<br>

{% endblock %}

APPfoto/templates/APPfoto/home.html
{% extends 'base.html' %}

{% block title %} Home di Super Gallery {% endblock %}

{% block header1 %}
  <h1>Home di Super Gallery</h1>
  <p>Welcome
    {% if user.is_authenticated %}
     {{ user.username }}
    {% else %}
    Utente non registrato, <br> Wait a minute, who are you?
    {% endif %}
  </p>
{% endblock %}

{% block content %}

<h2>Cosa si fa di bello?</h2>

<br>

<div class="list-group">
  <a href="{% url 'APPfoto:cercaFoto' %}" class="list-group-item list-group-item-info">Cerca una foto</a>
  <a href="{% url 'APPfoto:listafoto' %}" class="list-group-item list-group-item-info">Elenco delle Foto</a>
  <a href="{% url 'APPfoto:situation' %}" class="list-group-item list-group-item-info">Come siamo messi?</a>
</div>

<br>

{% if user.is_staff %}
<br>
<a href="{% url 'registrafotografo' %}" class="list-group-item list-group-item-danger">Iscrivi un fotografo alla gilda</a>
<br>
{% endif %}


{% if "Fotografi" in user.groups.all.0.name or user.is_staff %}
<br>
<!-- <a href="{ url 'gestione:situationb' %}" class="list-group-item list-group-item-warning">Situazione Biblioteca</a> -->
<a href="{% url 'APPfoto:creafoto' %}" class="list-group-item list-group-item-warning">Aggiungi una foto</a>
<!-- <a href="{ url 'gestione:creacopia' %}" class="list-group-item list-group-item-warning">Aggiungi una copia</a> -->
<br>
{% endif %}


{% endblock %}

APPfoto/templates/APPfoto/lista_foto.html
{% extends 'base.html' %}

{% block title %} Elenco Foto{% endblock %}

{% load static %}

{% block header1 %}
  <h1>Elenco Foto</h1>
{% endblock %}

{% block content %}
<h2> {{ view.nome }} {{ object_list.count }} Foto </h2>

<br>
{% if object_list %}
    {% for f in object_list %}
    <br>
    <div class="card">
        <img src="../../..{% static f.actual_photo %}" alt= f.name height="500" width="500" >
        <div class="card-body">
            <h5 class="card-title">{{ f.nome }}</h5>
            {% if f.landscape %}
                <p class="card-text">foto scattata da {{ f.artist_name }} in formato Landscape</p>
            {% else %}
               <p class="card-text">foto scattata da {{ f.artist_name }} in formato Portrait</p>
            {% endif %}
            Spero ti piaccia
        </div>
        <div class="card-footer">
            Questa foto potrebbe piacerti
        </div>
    </div>
    <br>
    {% endfor %}
{% else %}
    <p>No photos available. Redirecting...</p>
    <script>
         setTimeout(function() {
            window.location.href = "{% url 'APPfoto:search_wrong_colour' %}";
        }, 3000);  // Redirect after 3 seconds
    </script>
{% endif %}
<br>

{% endblock %}

APPfoto/templates/APPfoto/search.html
{% extends 'base.html' %}

{% block title %} Cerca tra le foto{% endblock %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">



{% block header1 %}
  <h1>Cerca tra le foto</h1>
{% endblock %}

{% block content %}

<h2> Cerca tra le foto </h2>

<br>

{% if redirect_param %}

    <br>
    Sei stato rimandato a questa pagina perchè la ricerca non ha prodotto risultati <br>

    Ti ricordo che i colori disponibili sono: <br>
    Black,Dark Blue, Green, Gray, Light Blue, Orange, Pink, Purple, Red, White e Yellow.


<br>

{% else %}
    Sei in modalità di ricerca normale.
    <div class="d-flex justify-content-center">
        {% crispy form %}
    </div>
{% endif %}

<br>

{% endblock %}

APPfoto/templates/APPfoto/search_wrong_colour.html
{% extends 'base.html' %}

{% block title %} Cerca tra le foto{% endblock %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block header1 %}
  <h1>Cerca tra le foto</h1>
{% endblock %}

{% block content %}

<h2> Cerca tra le foto </h2>

<br>

{% if form.errors %}
<div class="alert alert-danger" style="background-color: rgba(255, 0, 0, 0.2);">
  <strong>Error:</strong> HAVE YOU EVER KILLED WITH ALL THE COLOURS OF THE WIND?.
</div>
{% endif %}

<br>

<div class="d-flex justify-content-center">
  {% crispy form %}
</div>
<br>
    Sei stato rimandato a questa pagina perchè la ricerca non ha prodotto risultati <br>

    Ti ricordo che i colori disponibili sono: <br>
    Black,Dark Blue, Green, Gray, Light Blue, Orange, Pink, Purple, Red, White e Yellow.


<br>

{% endblock %}

APPfoto/templates/APPfoto/situation.html
{% extends 'base.html' %}


{% block title %} Home di {{user.username}} {% endblock %}

{% block header1 %}
  <h1>Home di {{user.username}} </h1>
  <p>Benvenuto
    {% if user.is_authenticated %}
     {{ user.username }}
    {% else %}
    Utente non registrato
        <br>
        Wait a minute, who are you?
    {% endif %}
  </p>
{% endblock %}

{% block content %}

<h2>troverò il modo di salvare che acquisti hai fatto</h2>

<p> Ulteriori dettagli </p>

<br>
 QUI DEVO MOSTRARE LE FOTO CHE HAI COMPRATO, COME FACCIAMO? BOH
<!-- { for c in listacopie %}
<br>
<div class="card">
  <div class="card-header">
     Copia con id {{ c.pk }}
  </div>
  <div class="card-body">
    <h5 class="card-title">{ c.libro.titolo }}</h5>
    <p class="card-text">Un libro di { c.libro.autore }} di ben { c.libro.pagine }} pagine...</p>

    <a href="{ url 'gestione:restituzione' c.pk %}" class="btn btn-info"> Restituiscimi </a>

  </div>
</div>
<br>
{endfor%}   -->

<br>

{% endblock %}

foto_commerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  <style>
  .header-background {
    background-image: url('/static/wallpaper.jpg');
    background-size: cover;
    background-position: top;
    background-repeat: no-repeat;
    color: white; /* Set the text color to contrast with the background */
  }
</style>

  {% endblock %}
  {% load crispy_forms_tags %}

</head>


<title>{% block title %} {% endblock %}</title>

<body>

<div class="jumbotron text-center header-background" style="margin-bottom:0">
  {% block header1 %}
    <h1>Header</h1>
    <p>Subtitle</p>
  {% endblock %}
</div>


{% if user.is_authenticated and "ok" in request.GET.login  %}

<div id="info" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Everybody say hello to {{user.username}} !</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p> Login avvenuto con successo, è un piacere riaverla tra noi signore </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Chiudi</button>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
      $("#info").modal('show');
  });
</script>

{% endif %}


<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    {% block navbar %}
    <a class="navbar-brand" href="{% url 'home' %}">Super Gallery</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">


        <li class="nav-item">
          <a class="nav-link" href="{% url 'APPfoto:home' %}">Er gestionale va qua</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'APPfoto:listafoto' %}">Lista delle foto</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'APPfoto:cercaFoto' %}">Sai già di cosa hai voglia? Cerca una foto</a>
        </li>

      </ul>
    </div>
    {% endblock %}
  </nav>



  <div class="container" style="margin-top:30px">

      <div class="col-sm-22">
        <center>

        {% block content %}
        <h2>QUI TITOLO ACCATTIVANTE</h2>
        <h5>Sottotitolo meno accattivante ma pur sempre rilevante</h5>
        <div class="fakeimg">Fake Image</div>
        <p>Did you ever hear the tragedy of Darth Plagueis the wise?</p>
        <p>I thought not, it's not a story the jedi would tell you </p>
        {% endblock %}
        <br>
        </center>
      </div>
    </div>


  <div class="jumbotron text-center" style="margin-bottom:0">
    {% block footer %}

      {% if user.is_authenticated %}
      <a class="btn btn-info" href="{% url 'logout' %}" role="button">Logout</a>
      {% else %}
      <a class="btn btn-info" href="{% url 'register' %}" role="button">Sei nuovo? Registrati</a>
      <a class="btn btn-info" href="{% url 'login' %}" role="button">Login</a>
      {% endif %}

      <a class="btn btn-warning" href="/admin/" role="button">Login dei VIP (fotografi)</a>

    {%  endblock %}
  </div>


  </body>
  </html>

foto_commerce/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Super Gallery {% endblock %}

{% block header1 %}
  <h1>Super Gallery</h1>
  <p>Welcome to the Super Gallery
    <br>
    Please, take a seat, young Skywalker </p>
{% endblock %}

{% block content %}

<h2>Home di Super Gallery</h2>
<h5>Now 0% Galactus-free</h5>
<img src="{% static '/wallpaper.jpg' %}" width="800"  height="400px" alt="First wallpaper">
<p>Guardati pure intorno, fai come se non ci fossi</p>

{% endblock %}

foto_commerce/templates/user_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block title %} Creazione Utente {{ form.user_group_name }} {% endblock %}

{% block header1 %}
  <h1>Registrati ora!</h1>
  <p>Compilare tutti i campi</p>
{% endblock %}

{% block content %}

<form method="post"> {% csrf_token %}

  {{form | crispy}}

  <input type="submit" class="btn btn-success" value="Conferma e Registrati">

  </form>

{% endblock %}

{% block footer %} {% endblock %}